server:
  port: 8100

spring:
  datasource:
    driverClassName: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://127.0.0.1:3306/bootcamp_2408"
    username: "root"
    password: "admin1234"
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    # Hibernate ddl auto (create, create-drop, validate, update, none)