FROM openjdk:17
LABEL maintainer="itsupport@gmail.com"
ADD target/demo-sb-helloworld-0.0.1-SNAPSHOT.jar demo-sb-helloworld-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","demo-sb-helloworld-0.0.1-SNAPSHOT.jar"]
EXPOSE 8090